### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/errormail#1]
Es gibt offenbar noch kein Release im Installer. Wollen wir eins machen, oder ist das AddOn noch nicht produktionsfertig?

**Comment by phoebusryan** [comment]
Ich nutze es bereits produktiv. Müsste es einfach mal in den Installer packen. Ich habs einfach mal nur hier hochgeladen, damit evtl. Feedback kommt...

**Comment by AWqxKAWERbXo** [comment]
Feedback wäre deutlich früher gekommen, wenn es mir im Installer über den Weg gelaufen wäre. Ich denke, der bessere Weg ist es, so etwas frühzeitig in den Installer zu bringen und als alpha zu kennzeichnen.

**Comment by phoebusryan** [comment]
Das Addon wird nicht veröffentlicht und wird mit dem phpmailer zusammengefügt. Deshalb ist es aktuell nicht im Installer.

**Comment by skerbis** [comment]
bin dabei, habe auch entsprechende Vorbereitungen durchgeführt.

**Comment by AWqxKAWERbXo** [comment]
Danke @skerbis

**Comment by schuer** [comment]
@skerbis Cool, dass du’s machst. Aber willst du das Issue vielleicht nicht lieber erst schließen, wenn das Release auch gemacht worden ist?

**Comment by skerbis** [comment]
https://github.com/redaxo/redaxo/pull/1769

**Comment by skerbis** [comment]
https://github.com/redaxo/redaxo/pull/1769#issuecomment-393533929 ... es wird erstmal in FOR weitergeführt. Und dann schauen wir mal wie die Erfahrungen sind. Sofern @phoebusryan  nichts dagegen hat, würde ich das AddOn übernehmen und es weiterentwickeln.

**Comment by phoebusryan** [comment]
Genau, es wird in den phpmailer integriert und ich hab nichts dagegen. Deshalb closed.

**Comment by schuer** [comment]
Missverständnis. Es wird bei FOR weitergeführt.
Und es gibt nachwievor kein Release.

**Comment by skerbis** [comment]
@schuer warte einfach 2 - 5 Stunden, dann gibt's n Release

**Comment by skerbis** [comment]
@schuer  https://github.com/FriendsOfREDAXO/errormail/releases/tag/1.1.0
zack

**Comment by skerbis** [comment]
@schuer Zack: 2.0 
<img width="1157" alt="bildschirmfoto 2018-06-02 um 03 24 59" src="https://user-images.githubusercontent.com/791247/40879008-e2c2d7fc-6699-11e8-950c-5785051fd25e.png">
